#!/usr/bin/env bash
set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${BLUE}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }

INSTALL_DIR="/opt/shipyard"
IMAGE_PREFIX="${IMAGE_PREFIX:-shipyard}"

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}"
echo "  ███████╗██╗  ██╗██╗██████╗ ██╗   ██╗ █████╗ ██████╗ ██████╗ "
echo "  ██╔════╝██║  ██║██║██╔══██╗╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗"
echo "  ███████╗███████║██║██████╔╝ ╚████╔╝ ███████║██████╔╝██║  ██║"
echo "  ╚════██║██╔══██║██║██╔═══╝   ╚██╔╝  ██╔══██║██╔══██╗██║  ██║"
echo "  ███████║██║  ██║██║██║        ██║   ██║  ██║██║  ██║██████╔╝"
echo "  ╚══════╝╚═╝  ╚═╝╚═╝╚═╝        ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ "
echo -e "${RESET}"
echo -e "${BOLD}  Self-hosted container orchestration platform${RESET}"
echo ""

# ── Prerequisites ─────────────────────────────────────────────────────────────
info "Checking prerequisites..."

command -v docker >/dev/null 2>&1 || error "Docker is not installed. Install it from https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || error "Docker Compose v2 plugin not found. Install it: https://docs.docker.com/compose/install/"
command -v curl >/dev/null 2>&1 || error "curl is not installed. Run: apt-get install -y curl"
command -v openssl >/dev/null 2>&1 || error "openssl is not installed. Run: apt-get install -y openssl"

success "Prerequisites OK"

# ── Already installed? ────────────────────────────────────────────────────────
if [[ -f "${INSTALL_DIR}/docker-compose.yml" ]]; then
    warn "Shipyard appears to already be installed at ${INSTALL_DIR}."
    read -rp "Re-install / overwrite? [y/N] " REINSTALL
    [[ "${REINSTALL,,}" == "y" ]] || { info "Aborted."; exit 0; }
fi

# ── Gather config ─────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}Configuration${RESET}"
echo "─────────────────────────────────────────────"

read -rp "Domain name (e.g. app.example.com): " DOMAIN
[[ -n "${DOMAIN}" ]] || error "Domain name is required."

read -rp "Email for Let's Encrypt certificates: " ACME_EMAIL
[[ -n "${ACME_EMAIL}" ]] || error "Email is required for Let's Encrypt."

read -rp "Image tag [latest]: " TAG
TAG="${TAG:-latest}"

read -rp "Enable HTTPS / TLS? [Y/n]: " USE_HTTPS
USE_HTTPS="${USE_HTTPS:-y}"

if [[ "${USE_HTTPS,,}" == "y" || "${USE_HTTPS,,}" == "yes" ]]; then
    PROTOCOL="https"
    TRAEFIK_TLS="true"
else
    PROTOCOL="http"
    TRAEFIK_TLS="false"
fi

# ── Secrets ───────────────────────────────────────────────────────────────────
info "Generating secrets..."
JWT_SECRET="$(openssl rand -hex 32)"
SECRET_KEY="$(openssl rand -hex 32)"
POSTGRES_PASSWORD="$(openssl rand -hex 16)"

# ── Directories ───────────────────────────────────────────────────────────────
info "Creating directories at ${INSTALL_DIR}..."
mkdir -p "${INSTALL_DIR}/data" "${INSTALL_DIR}/certs" "${INSTALL_DIR}/traefik/dynamic"
chmod 700 "${INSTALL_DIR}"

# ── .env ──────────────────────────────────────────────────────────────────────
info "Writing ${INSTALL_DIR}/.env..."
cat > "${INSTALL_DIR}/.env" <<ENV
# Shipyard — generated by install.sh
# DO NOT commit this file to version control.

DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}
TAG=${TAG}
IMAGE_PREFIX=${IMAGE_PREFIX}
PROTOCOL=${PROTOCOL}

# Database
POSTGRES_USER=shipyard
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=shipyard
SHIPYARD__DATABASE__URL=postgres://shipyard:${POSTGRES_PASSWORD}@postgres:5432/shipyard
SHIPYARD__DATABASE__MAX_CONNECTIONS=10

# MQTT
SHIPYARD__MQTT__HOST=mqtt
SHIPYARD__MQTT__PORT=1883
SHIPYARD__MQTT__CLIENT_ID=shipyard-api

# Auth
SHIPYARD__AUTH__JWT_SECRET=${JWT_SECRET}
SHIPYARD__AUTH__ACCESS_TOKEN_EXPIRY=3600
SHIPYARD__AUTH__REFRESH_TOKEN_EXPIRY=604800
SHIPYARD__AUTH__SECRET_KEY=${SECRET_KEY}

# Server
SHIPYARD__SERVER__HOST=0.0.0.0
SHIPYARD__SERVER__PORT=3001

# Docker
SHIPYARD__DOCKER__LABEL_PREFIX=platform

# Traefik
SHIPYARD__TRAEFIK__NETWORK=platform_proxy
SHIPYARD__TRAEFIK__ENTRYPOINT_HTTP=web
SHIPYARD__TRAEFIK__ENTRYPOINT_HTTPS=websecure
SHIPYARD__TRAEFIK__CERT_RESOLVER=letsencrypt
SHIPYARD__TRAEFIK__DYNAMIC_CONFIG_DIR=${INSTALL_DIR}/traefik/dynamic

# Data
SHIPYARD__DATA_DIR=${INSTALL_DIR}/data

RUST_LOG=shipyard=info,tower_http=warn
ENV
chmod 600 "${INSTALL_DIR}/.env"

# ── rmqtt.toml ────────────────────────────────────────────────────────────────
info "Writing ${INSTALL_DIR}/rmqtt.toml..."
cat > "${INSTALL_DIR}/rmqtt.toml" <<'RMQTT'
[node]
id = 1

[log]
level = "warn"

[listeners.tcp]
addr = "0.0.0.0:1883"

[listeners.websocket]
addr = "0.0.0.0:8083"

[mqtt]
max_packet_size = 1048576
RMQTT

# ── Traefik static config ─────────────────────────────────────────────────────
info "Writing Traefik config..."
cat > "${INSTALL_DIR}/traefik/traefik.yml" <<TRAEFIK
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: platform_proxy
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

api:
  dashboard: false
TRAEFIK

# ── Traefik dynamic config ─────────────────────────────────────────────────────
cat > "${INSTALL_DIR}/traefik/dynamic/shipyard.yml" <<DYNAMIC
http:
  routers:
    shipyard-frontend:
      rule: "Host(\`${DOMAIN}\`)"
      entryPoints: [websecure]
      service: shipyard-frontend
      tls:
        certResolver: letsencrypt

    shipyard-backend:
      rule: "Host(\`api.${DOMAIN}\`)"
      entryPoints: [websecure]
      service: shipyard-backend
      tls:
        certResolver: letsencrypt

  services:
    shipyard-frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"

    shipyard-backend:
      loadBalancer:
        servers:
          - url: "http://backend:3001"
DYNAMIC

# ── docker-compose.yml ────────────────────────────────────────────────────────
info "Writing ${INSTALL_DIR}/docker-compose.yml..."
cat > "${INSTALL_DIR}/docker-compose.yml" <<COMPOSE
services:

  postgres:
    image: postgres:16-alpine
    container_name: shipyard-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: \${POSTGRES_USER}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_DB: \${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shipyard"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  redis:
    image: redis:7-alpine
    container_name: shipyard-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - internal

  mqtt:
    image: rmqtt/rmqtt:latest
    container_name: shipyard-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8083:8083"
    volumes:
      - ${INSTALL_DIR}/rmqtt.toml:/app/rmqtt.toml:ro
      - rmqtt_data:/app/data
    networks:
      - internal

  backend:
    image: \${IMAGE_PREFIX}/shipyard-backend:\${TAG}
    container_name: shipyard-backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - ${INSTALL_DIR}/data:/opt/shipyard/data
      - ${INSTALL_DIR}/traefik/dynamic:/etc/traefik/dynamic
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mqtt:
        condition: service_started
    networks:
      - internal
      - platform_proxy

  frontend:
    image: \${IMAGE_PREFIX}/shipyard-frontend:\${TAG}
    container_name: shipyard-frontend
    restart: unless-stopped
    environment:
      ORIGIN: "${PROTOCOL}://${DOMAIN}"
      PRIVATE_API_URL: "http://backend:3001"
    depends_on:
      - backend
    networks:
      - internal
      - platform_proxy

  traefik:
    image: traefik:v3.1
    container_name: shipyard-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${INSTALL_DIR}/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${INSTALL_DIR}/traefik/dynamic:/etc/traefik/dynamic:ro
      - traefik_certs:/letsencrypt
    networks:
      - platform_proxy

networks:
  internal:
    name: shipyard_internal
  platform_proxy:
    name: platform_proxy
    external: true

volumes:
  postgres_data:
  redis_data:
  rmqtt_data:
  traefik_certs:
COMPOSE

# ── Docker network ────────────────────────────────────────────────────────────
info "Ensuring platform_proxy network exists..."
docker network inspect platform_proxy >/dev/null 2>&1 \
    || docker network create platform_proxy

# ── Pull images ───────────────────────────────────────────────────────────────
info "Pulling Docker images (this may take a few minutes)..."
cd "${INSTALL_DIR}"
docker compose pull

# ── Start ─────────────────────────────────────────────────────────────────────
info "Starting Shipyard..."
docker compose up -d

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════╗${RESET}"
echo -e "${GREEN}${BOLD}║       Shipyard installed successfully!        ║${RESET}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "  Dashboard:  ${BOLD}${PROTOCOL}://${DOMAIN}${RESET}"
echo -e "  API:        ${BOLD}${PROTOCOL}://api.${DOMAIN}${RESET}"
echo -e "  Install dir: ${INSTALL_DIR}"
echo ""
echo -e "  Useful commands:"
echo -e "    ${BOLD}cd ${INSTALL_DIR} && docker compose logs -f${RESET}   (follow all logs)"
echo -e "    ${BOLD}docker compose ps${RESET}                              (check status)"
echo -e "    ${BOLD}docker compose restart backend${RESET}                 (restart API)"
echo ""
echo -e "  ${YELLOW}First run:${RESET} visit ${PROTOCOL}://${DOMAIN}/setup to create your admin account."
echo ""
