use axum::{
    extract::{Path, State},
    http::StatusCode,
    routing::{delete, get, post},
    Json, Router,
};
use serde::Deserialize;
use std::fmt::Write as FmtWrite;
use uuid::Uuid;

use shipyard_common::error::AppError;
use shipyard_common::types::{ApiResponse, MqttPayload};
use shipyard_db::models::{Domain, Network, Volume};

use crate::auth::AuthUser;
use crate::error::ApiAppError;
use crate::middleware::rbac::{require_project_access, require_project_permission, require_service_access, require_service_permission};
use crate::AppState;

// ─── Traefik dynamic config writer ───────────────────────────────────────────

/// nip.io and traefik.me are wildcard DNS convenience domains.
/// They must never use certResolver — each unique subdomain would consume a LE
/// certificate slot, exhausting the rate limit very quickly.
/// These domains are served over plain HTTP instead.
fn is_convenience_domain(hostname: &str) -> bool {
    hostname.ends_with(".nip.io") || hostname.ends_with(".traefik.me")
}

/// Converts a hostname into a safe Traefik router/service name.
/// Each domain gets a unique name, avoiding duplicate YAML keys when a service
/// has multiple domains attached.
fn hostname_to_router_name(hostname: &str) -> String {
    hostname
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect::<String>()
        .to_ascii_lowercase()
}

/// Regenerates the Traefik file-provider dynamic config for a service's domains.
///
/// Writes `{dir}/{slug}.yml`. If there are no domains the file is removed.
/// Silently skips if `dynamic_config_dir` is not configured.
async fn sync_traefik_dynamic_config(
    db: &sqlx::PgPool,
    service_id: Uuid,
    label_prefix: &str,
    entrypoint_http: &str,
    entrypoint_https: &str,
    dynamic_config_dir: Option<&str>,
) {
    let Some(dir) = dynamic_config_dir else { return };

    // Resolve slug and type for file name / upstream selection
    let (slug, svc_type): (String, String) = sqlx::query_as(
        "SELECT slug, type::text FROM services WHERE id = $1",
    )
    .bind(service_id)
    .fetch_optional(db)
    .await
    .ok()
    .flatten()
    .unwrap_or_else(|| (service_id.to_string(), String::new()));

    let path = std::path::Path::new(dir).join(format!("{slug}.yml"));

    // Fetch all current domains for this service
    let rows: Vec<(String, bool, String, Option<i32>, String)> = match sqlx::query_as(
        "SELECT hostname, tls_enabled, cert_provider, port, traefik_router_name
         FROM domains WHERE service_id = $1 ORDER BY created_at ASC",
    )
    .bind(service_id)
    .fetch_all(db)
    .await
    {
        Ok(r) => r,
        Err(e) => {
            tracing::warn!("sync_traefik_dynamic_config: DB error: {e}");
            return;
        }
    };

    if rows.is_empty() {
        let _ = tokio::fs::remove_file(&path).await;
        tracing::info!("Removed Traefik dynamic config (no domains): {path:?}");
        return;
    }

    // Static sites are all served by the shared nginx container, not by a per-service
    // Docker Swarm service. Everything else routes to its own Swarm service.
    let upstream_host = if svc_type == "static" {
        "shipyard-nginx-static".to_string()
    } else {
        format!("{label_prefix}-{service_id}")
    };

    let mut out = String::from("# Auto-generated by Shipyard — do not edit manually\n");
    out.push_str("http:\n");
    out.push_str("  routers:\n");

    for (hostname, tls_enabled, cert_provider, _port, _stored_router_name) in &rows {
        // Derive a unique router name from the hostname so multiple domains on the
        // same service never produce duplicate YAML keys (which silently drop entries).
        let rn = hostname_to_router_name(hostname);
        let convenience = is_convenience_domain(hostname);

        // HTTP router (global entryPoint redirect sends plain-HTTP requests to HTTPS)
        let _ = write!(out, "    {rn}-http:\n");
        let _ = write!(out, "      rule: \"Host(`{hostname}`)\"\n");
        let _ = write!(out, "      entryPoints:\n");
        let _ = write!(out, "        - {entrypoint_http}\n");
        let _ = write!(out, "      service: {rn}\n");

        // Always create an HTTPS router so the domain is reachable when the global
        // HTTP→HTTPS redirect is active. Convenience and tls_enabled=false domains
        // use a self-signed fallback cert; real custom domains use certResolver.
        let _ = write!(out, "    {rn}-https:\n");
        let _ = write!(out, "      rule: \"Host(`{hostname}`)\"\n");
        let _ = write!(out, "      entryPoints:\n");
        let _ = write!(out, "        - {entrypoint_https}\n");
        // shipyard-error-pages replaces 404 responses with the branded Shipyard HTML page.
        let _ = write!(out, "      middlewares:\n");
        let _ = write!(out, "        - shipyard-error-pages@file\n");
        if convenience || !*tls_enabled {
            // nip.io / traefik.me / tls_enabled=false: self-signed cert (no LE slot consumed).
            let _ = write!(out, "      tls: {{}}\n");
        } else {
            // Real custom domain with TLS: Let's Encrypt via certResolver.
            let _ = write!(out, "      tls:\n");
            let _ = write!(out, "        certResolver: {cert_provider}\n");
        }
        let _ = write!(out, "      service: {rn}\n");
    }

    out.push_str("  services:\n");

    for (hostname, _, _, port, _) in &rows {
        let rn = hostname_to_router_name(hostname);
        let backend_port = port.unwrap_or(80);
        let _ = write!(out, "    {rn}:\n");
        let _ = write!(out, "      loadBalancer:\n");
        let _ = write!(out, "        servers:\n");
        let _ = write!(out, "          - url: \"http://{upstream_host}:{backend_port}\"\n");
    }

    if let Err(e) = tokio::fs::create_dir_all(dir).await {
        tracing::warn!("sync_traefik_dynamic_config: could not create dir '{dir}': {e}");
        return;
    }
    if let Err(e) = tokio::fs::write(&path, out.as_bytes()).await {
        tracing::warn!("sync_traefik_dynamic_config: could not write '{path:?}': {e}");
    } else {
        tracing::info!("Wrote Traefik dynamic config: {path:?}");
    }
}

/// Regenerates the nginx `server_name` line in the static site's conf file.
///
/// Called whenever domains are added or removed so nginx knows which hostnames to
/// accept for this site without waiting for the next deployment.
async fn sync_static_nginx_conf(db: &sqlx::PgPool, service_id: Uuid, data_dir: &str) {
    // Only applies to static services
    let svc_type: Option<String> = sqlx::query_scalar("SELECT type::text FROM services WHERE id = $1")
        .bind(service_id)
        .fetch_optional(db)
        .await
        .ok()
        .flatten();
    if svc_type.as_deref() != Some("static") {
        return;
    }

    let slug: Option<String> = sqlx::query_scalar("SELECT slug FROM services WHERE id = $1")
        .bind(service_id)
        .fetch_optional(db)
        .await
        .ok()
        .flatten();
    let Some(slug) = slug else { return };

    let sites_base = format!("{data_dir}/static");
    let conf_path = format!("{sites_base}/conf.d/{slug}.conf");

    let existing = match tokio::fs::read_to_string(&conf_path).await {
        Ok(c) => Some(c),
        Err(_) => None,
    };

    // Fetch the current full domain list (after the DB mutation that triggered this call)
    let domains: Vec<String> = sqlx::query_scalar(
        "SELECT hostname FROM domains WHERE service_id = $1 ORDER BY created_at ASC",
    )
    .bind(service_id)
    .fetch_all(db)
    .await
    .unwrap_or_default();

    if domains.is_empty() {
        // All domains removed — delete the conf so the app is no longer served on a wildcard.
        // The default_server block will return 404 for requests without a known hostname.
        if let Err(e) = tokio::fs::remove_file(&conf_path).await {
            if e.kind() != std::io::ErrorKind::NotFound {
                tracing::warn!("sync_static_nginx_conf: could not remove '{conf_path}': {e}");
            }
        }
    } else {
        let updated = match existing {
            Some(ref existing_conf) => {
                // Splice new server_name into existing conf, preserving all other directives
                let server_name_value = domains.join(" ");
                existing_conf
                    .lines()
                    .map(|line| {
                        if line.trim_start().starts_with("server_name ") {
                            format!("    server_name {server_name_value};")
                        } else {
                            line.to_string()
                        }
                    })
                    .collect::<Vec<_>>()
                    .join("\n")
            }
            None => {
                // Conf missing — generate from scratch using the canonical serve root.
                // nginx handles a not-yet-existing root gracefully (returns 404) so we
                // don't gate on whether the deployment directory exists yet.
                let serve_root = format!("{sites_base}/{service_id}/current/public");
                shipyard_engine::static_site::render_nginx_site_conf(
                    &service_id.to_string(),
                    &domains,
                    &serve_root,
                    &sites_base,
                    &Default::default(),
                )
            }
        };

        // Ensure conf.d exists (may not exist if nginx container hasn't been started yet).
        let conf_dir = std::path::Path::new(&conf_path)
            .parent()
            .map(|p| p.to_string_lossy().into_owned())
            .unwrap_or_default();
        if !conf_dir.is_empty() {
            if let Err(e) = tokio::fs::create_dir_all(&conf_dir).await {
                tracing::warn!("sync_static_nginx_conf: could not create conf dir '{conf_dir}': {e}");
                return;
            }
        }

        if let Err(e) = tokio::fs::write(&conf_path, updated.as_bytes()).await {
            tracing::warn!("sync_static_nginx_conf: could not write '{conf_path}': {e}");
            return;
        }
        tracing::info!("sync_static_nginx_conf: wrote {conf_path}");
    }

    let reload = tokio::process::Command::new("docker")
        .args(["exec", "shipyard-nginx-static", "nginx", "-s", "reload"])
        .output()
        .await;
    match reload {
        Ok(o) if o.status.success() => {
            tracing::info!("sync_static_nginx_conf: nginx reloaded for service {service_id}");
        }
        Ok(o) => {
            let stderr = String::from_utf8_lossy(&o.stderr);
            tracing::warn!("sync_static_nginx_conf: nginx reload non-zero: {stderr}");
        }
        Err(e) => {
            tracing::warn!("sync_static_nginx_conf: docker not in PATH: {e}");
        }
    }
}

// ─── Request types ────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
pub struct CreateDomainRequest {
    pub hostname: String,
    #[serde(default = "default_true")]
    pub tls_enabled: bool,
    #[serde(default = "default_cert_provider")]
    pub cert_provider: String,
    pub port: Option<i32>,
}

fn default_cert_provider() -> String {
    "letsencrypt".to_string()
}

#[derive(Debug, Deserialize)]
pub struct CreateVolumeRequest {
    pub name: String,
    pub mount_path: String,
    pub driver: Option<String>,
    pub size_mb: Option<i32>,
}

#[derive(Debug, Deserialize)]
pub struct CreateNetworkRequest {
    pub name: String,
    pub driver: Option<String>,
    pub subnet: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct AttachServiceRequest {
    pub service_id: Uuid,
}

fn default_true() -> bool {
    true
}

// ─── Router ───────────────────────────────────────────────────────────────────

pub fn routes() -> Router<AppState> {
    Router::new()
        // Domains
        .route(
            "/services/:service_id/domains",
            get(list_domains).post(create_domain),
        )
        .route(
            "/services/:service_id/domains/:domain_id",
            delete(delete_domain),
        )
        .route(
            "/services/:service_id/domains/:domain_id/check-dns",
            get(check_domain_dns),
        )
        // Service-scoped volumes (attach to a specific service)
        .route(
            "/services/:service_id/volumes",
            get(list_volumes).post(create_volume),
        )
        .route(
            "/services/:service_id/volumes/:volume_id",
            delete(delete_volume),
        )
        // Project-scoped standalone volumes
        .route(
            "/projects/:project_id/volumes",
            get(list_project_volumes).post(create_project_volume),
        )
        .route(
            "/projects/:project_id/volumes/:volume_id",
            get(get_project_volume).delete(delete_project_volume),
        )
        .route(
            "/projects/:project_id/volumes/:volume_id/attach",
            post(attach_volume_to_service),
        )
        // Networks
        .route(
            "/projects/:project_id/networks",
            get(list_networks).post(create_network),
        )
        .route(
            "/projects/:project_id/networks/:network_id",
            get(get_network).delete(delete_network),
        )
        .route(
            "/projects/:project_id/networks/:network_id/attach",
            post(attach_service),
        )
        .route(
            "/projects/:project_id/networks/:network_id/services/:service_id",
            delete(detach_service),
        )
        .route(
            "/services/:service_id/networks",
            get(list_service_networks),
        )
}

// ─── Domain Handlers ──────────────────────────────────────────────────────────

/// GET /services/:service_id/domains
async fn list_domains(
    auth_user: AuthUser,
    Path(service_id): Path<Uuid>,
    State(state): State<AppState>,
) -> Result<Json<ApiResponse<Vec<Domain>>>, ApiAppError> {
    require_service_access(&state.db, auth_user.user_id, service_id).await.map_err(ApiAppError)?;
    let domains = sqlx::query_as::<_, Domain>(
        "SELECT id, service_id, hostname, tls_enabled, traefik_router_name, cert_provider, port, created_at
         FROM domains
         WHERE service_id = $1
         ORDER BY created_at ASC",
    )
    .bind(service_id)
    .fetch_all(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    Ok(Json(ApiResponse::ok(domains)))
}

/// POST /services/:service_id/domains
async fn create_domain(
    auth_user: AuthUser,
    Path(service_id): Path<Uuid>,
    State(state): State<AppState>,
    Json(body): Json<CreateDomainRequest>,
) -> Result<(StatusCode, Json<ApiResponse<Domain>>), ApiAppError> {
    require_service_permission(&state.db, auth_user.user_id, service_id, "domain:write").await.map_err(ApiAppError)?;
    if body.hostname.is_empty() {
        return Err(ApiAppError(AppError::BadRequest("hostname is required".to_string())));
    }

    // Verify service exists
    let service_exists: Option<(bool,)> = sqlx::query_as::<_, (bool,)>(
        "SELECT TRUE FROM services WHERE id = $1",
    )
    .bind(service_id)
    .fetch_optional(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    if service_exists.is_none() {
        return Err(ApiAppError(AppError::NotFound(format!(
            "Service '{}' not found",
            service_id
        ))));
    }

    let domain_id = Uuid::now_v7();
    // Router name is hostname-derived (unique per domain) so multiple domains on
    // the same service never collide in the Traefik YAML file.
    let traefik_router_name = hostname_to_router_name(&body.hostname);

    // Convenience wildcard-DNS domains must never request LE certs.
    let tls_enabled = body.tls_enabled && !is_convenience_domain(&body.hostname);

    let domain = sqlx::query_as::<_, Domain>(
        "INSERT INTO domains (id, service_id, hostname, tls_enabled, traefik_router_name, cert_provider, port, created_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
         RETURNING id, service_id, hostname, tls_enabled, traefik_router_name, cert_provider, port, created_at",
    )
    .bind(domain_id)
    .bind(service_id)
    .bind(&body.hostname)
    .bind(tls_enabled)
    .bind(&traefik_router_name)
    .bind(&body.cert_provider)
    .bind(body.port)
    .fetch_one(&state.db)
    .await
    .map_err(|e| {
        let msg = e.to_string();
        if msg.contains("unique") || msg.contains("duplicate") {
            ApiAppError(AppError::Conflict(format!(
                "Domain '{}' already exists",
                body.hostname
            )))
        } else {
            ApiAppError(AppError::Database(msg))
        }
    })?;

    // Write Traefik file-provider config (no-op when dynamic_config_dir is unset)
    sync_traefik_dynamic_config(
        &state.db,
        service_id,
        &state.config.docker.label_prefix,
        &state.config.traefik.entrypoint_http,
        &state.config.traefik.entrypoint_https,
        state.config.traefik.dynamic_config_dir.as_deref(),
    ).await;

    // For static sites: update the nginx server_name so the site responds on the new domain immediately.
    sync_static_nginx_conf(&state.db, service_id, &state.config.data_dir).await;

    // Publish MQTT topology event so the canvas adds the new domain node.
    if let Ok(Some((project_id, org_id))) = sqlx::query_as::<_, (Uuid, Uuid)>(
        "SELECT p.id, p.org_id
         FROM services s
         JOIN projects p ON p.id = s.project_id
         WHERE s.id = $1",
    )
    .bind(service_id)
    .fetch_optional(&state.db)
    .await
    {
        let topic = shipyard_mqtt::topics::topology(org_id, project_id);
        let payload = MqttPayload::new("topology.changed")
            .with_meta(serde_json::json!({ "resource": "domain", "domain_id": domain.id }));
        state.mqtt.publish_status(&topic, &payload).await.ok();
    }

    Ok((StatusCode::CREATED, Json(ApiResponse::ok(domain))))
}

/// DELETE /services/:service_id/domains/:domain_id
async fn delete_domain(
    auth_user: AuthUser,
    Path((service_id, domain_id)): Path<(Uuid, Uuid)>,
    State(state): State<AppState>,
) -> Result<Json<ApiResponse<serde_json::Value>>, ApiAppError> {
    require_service_permission(&state.db, auth_user.user_id, service_id, "domain:write").await.map_err(ApiAppError)?;
    let rows_affected = sqlx::query(
        "DELETE FROM domains WHERE id = $1 AND service_id = $2",
    )
    .bind(domain_id)
    .bind(service_id)
    .execute(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?
    .rows_affected();

    if rows_affected == 0 {
        return Err(ApiAppError(AppError::NotFound(format!(
            "Domain '{}' not found",
            domain_id
        ))));
    }

    // Regenerate Traefik file-provider config after removal
    sync_traefik_dynamic_config(
        &state.db,
        service_id,
        &state.config.docker.label_prefix,
        &state.config.traefik.entrypoint_http,
        &state.config.traefik.entrypoint_https,
        state.config.traefik.dynamic_config_dir.as_deref(),
    ).await;

    // For static sites: update nginx server_name after the domain is removed.
    sync_static_nginx_conf(&state.db, service_id, &state.config.data_dir).await;

    if let Ok(Some((project_id, org_id))) = sqlx::query_as::<_, (Uuid, Uuid)>(
        "SELECT p.id, p.org_id FROM services s JOIN projects p ON p.id = s.project_id WHERE s.id = $1",
    )
    .bind(service_id)
    .fetch_optional(&state.db)
    .await
    {
        let topic = shipyard_mqtt::topics::topology(org_id, project_id);
        let payload = MqttPayload::new("topology.changed")
            .with_meta(serde_json::json!({ "resource": "domain", "domain_id": domain_id, "reason": "deleted" }));
        state.mqtt.publish_status(&topic, &payload).await.ok();
    }

    Ok(Json(ApiResponse::ok(serde_json::json!({
        "message": "Domain deleted successfully"
    }))))
}

/// GET /services/:service_id/domains/:domain_id/check-dns
async fn check_domain_dns(
    auth_user: AuthUser,
    Path((service_id, domain_id)): Path<(Uuid, Uuid)>,
    State(state): State<AppState>,
) -> Result<Json<ApiResponse<serde_json::Value>>, ApiAppError> {
    require_service_access(&state.db, auth_user.user_id, service_id).await.map_err(ApiAppError)?;
    let row = sqlx::query_as::<_, (String,)>(
        "SELECT hostname FROM domains WHERE id = $1 AND service_id = $2",
    )
    .bind(domain_id)
    .bind(service_id)
    .fetch_optional(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    let hostname = match row {
        Some((h,)) => h,
        None => return Err(ApiAppError(AppError::NotFound(format!("Domain '{}' not found", domain_id)))),
    };

    let lookup_target = format!("{}:80", hostname);
    let result = tokio::time::timeout(
        std::time::Duration::from_secs(5),
        tokio::net::lookup_host(&lookup_target),
    )
    .await;

    let (resolves, addresses) = match result {
        Ok(Ok(addrs)) => {
            let ips: Vec<String> = addrs.map(|a| a.ip().to_string()).collect();
            (!ips.is_empty(), ips)
        }
        _ => (false, vec![]),
    };

    Ok(Json(ApiResponse::ok(serde_json::json!({
        "hostname": hostname,
        "resolves": resolves,
        "addresses": addresses,
    }))))
}

// ─── Volume Handlers ──────────────────────────────────────────────────────────

/// GET /services/:service_id/volumes
async fn list_volumes(
    auth_user: AuthUser,
    Path(service_id): Path<Uuid>,
    State(state): State<AppState>,
) -> Result<Json<ApiResponse<Vec<Volume>>>, ApiAppError> {
    require_service_access(&state.db, auth_user.user_id, service_id).await.map_err(ApiAppError)?;
    let volumes = sqlx::query_as::<_, Volume>(
        "SELECT id, project_id, service_id, name, mount_path, driver, size_mb, created_at
         FROM volumes
         WHERE service_id = $1
         ORDER BY created_at ASC",
    )
    .bind(service_id)
    .fetch_all(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    Ok(Json(ApiResponse::ok(volumes)))
}

/// POST /services/:service_id/volumes
async fn create_volume(
    auth_user: AuthUser,
    Path(service_id): Path<Uuid>,
    State(state): State<AppState>,
    Json(body): Json<CreateVolumeRequest>,
) -> Result<(StatusCode, Json<ApiResponse<Volume>>), ApiAppError> {
    require_service_permission(&state.db, auth_user.user_id, service_id, "volume:write").await.map_err(ApiAppError)?;
    if body.name.is_empty() {
        return Err(ApiAppError(AppError::BadRequest("name is required".to_string())));
    }
    if body.mount_path.is_empty() {
        return Err(ApiAppError(AppError::BadRequest("mount_path is required".to_string())));
    }

    let service_exists: Option<(bool,)> = sqlx::query_as::<_, (bool,)>(
        "SELECT TRUE FROM services WHERE id = $1",
    )
    .bind(service_id)
    .fetch_optional(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    if service_exists.is_none() {
        return Err(ApiAppError(AppError::NotFound(format!(
            "Service '{}' not found",
            service_id
        ))));
    }

    let project_row: Option<(Uuid,)> = sqlx::query_as::<_, (Uuid,)>(
        "SELECT project_id FROM services WHERE id = $1",
    )
    .bind(service_id)
    .fetch_optional(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    let project_id = project_row.map(|(pid,)| pid);
    let driver = body.driver.unwrap_or_else(|| "local".to_string());
    let size_mb = body.size_mb.unwrap_or(1024);

    // Create Docker volume first; abort if Docker is unavailable.
    state.docker.create_volume(&body.name, &driver).await
        .map_err(|e| ApiAppError(AppError::Docker(e.to_string())))?;

    let volume = sqlx::query_as::<_, Volume>(
        "INSERT INTO volumes (id, project_id, service_id, name, mount_path, driver, size_mb, created_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
         RETURNING id, project_id, service_id, name, mount_path, driver, size_mb, created_at",
    )
    .bind(Uuid::now_v7())
    .bind(project_id)
    .bind(service_id)
    .bind(&body.name)
    .bind(&body.mount_path)
    .bind(&driver)
    .bind(size_mb)
    .fetch_one(&state.db)
    .await
    .map_err(|e| {
        // Docker volume was created but DB insert failed — clean up best-effort.
        let name = body.name.clone();
        let docker = state.docker.clone();
        tokio::spawn(async move {
            if let Err(re) = docker.remove_volume(&name).await {
                tracing::warn!("Failed to remove orphaned Docker volume '{name}': {re}");
            }
        });
        ApiAppError(AppError::Database(e.to_string()))
    })?;

    Ok((StatusCode::CREATED, Json(ApiResponse::ok(volume))))
}

/// DELETE /services/:service_id/volumes/:volume_id
async fn delete_volume(
    auth_user: AuthUser,
    Path((service_id, volume_id)): Path<(Uuid, Uuid)>,
    State(state): State<AppState>,
) -> Result<Json<ApiResponse<serde_json::Value>>, ApiAppError> {
    require_service_permission(&state.db, auth_user.user_id, service_id, "volume:write").await.map_err(ApiAppError)?;
    // Fetch first to get the volume name for Docker removal.
    let row: Option<(String,)> = sqlx::query_as::<_, (String,)>(
        "SELECT name FROM volumes WHERE id = $1 AND service_id = $2",
    )
    .bind(volume_id)
    .bind(service_id)
    .fetch_optional(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    let (volume_name,) = row.ok_or_else(|| {
        ApiAppError(AppError::NotFound(format!("Volume '{}' not found", volume_id)))
    })?;

    // Remove from Docker. A 404 means it's already gone — skip and clean up DB.
    match state.docker.remove_volume(&volume_name).await {
        Ok(_) => {}
        Err(AppError::Docker(ref msg)) if msg.contains("404") => {
            tracing::warn!("Volume '{volume_name}' not found in Docker (already removed), cleaning up DB");
        }
        Err(e) => return Err(ApiAppError(e)),
    }

    sqlx::query("DELETE FROM volumes WHERE id = $1 AND service_id = $2")
        .bind(volume_id)
        .bind(service_id)
        .execute(&state.db)
        .await
        .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    Ok(Json(ApiResponse::ok(serde_json::json!({ "message": "Volume deleted successfully" }))))
}

/// GET /projects/:project_id/volumes — list standalone (project-level) volumes.
async fn list_project_volumes(
    auth_user: AuthUser,
    Path(project_id): Path<Uuid>,
    State(state): State<AppState>,
) -> Result<Json<ApiResponse<Vec<Volume>>>, ApiAppError> {
    require_project_access(&state.db, auth_user.user_id, project_id).await.map_err(ApiAppError)?;
    let volumes = sqlx::query_as::<_, Volume>(
        "SELECT id, project_id, service_id, name, mount_path, driver, size_mb, created_at
         FROM volumes
         WHERE project_id = $1 AND service_id IS NULL
         ORDER BY created_at ASC",
    )
    .bind(project_id)
    .fetch_all(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    Ok(Json(ApiResponse::ok(volumes)))
}

/// POST /projects/:project_id/volumes/:volume_id/attach — link a standalone volume to a service.
async fn attach_volume_to_service(
    auth_user: AuthUser,
    Path((project_id, volume_id)): Path<(Uuid, Uuid)>,
    State(state): State<AppState>,
    Json(body): Json<serde_json::Value>,
) -> Result<Json<ApiResponse<serde_json::Value>>, ApiAppError> {
    require_project_permission(&state.db, auth_user.user_id, project_id, "volume:write").await.map_err(ApiAppError)?;
    let service_id: Uuid = body["service_id"]
        .as_str()
        .and_then(|s| s.parse().ok())
        .ok_or_else(|| ApiAppError(AppError::BadRequest("service_id is required".to_string())))?;

    let updated = sqlx::query(
        "UPDATE volumes
         SET service_id = $1, project_id = NULL
         WHERE id = $2 AND project_id = $3 AND service_id IS NULL",
    )
    .bind(service_id)
    .bind(volume_id)
    .bind(project_id)
    .execute(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    if updated.rows_affected() == 0 {
        return Err(ApiAppError(AppError::NotFound(
            format!("Volume '{volume_id}' not found or already attached to a service"),
        )));
    }

    Ok(Json(ApiResponse::ok(serde_json::json!({ "message": "Volume attached to service" }))))
}

/// GET /projects/:project_id/volumes/:volume_id — fetch a single volume by ID.
async fn get_project_volume(
    auth_user: AuthUser,
    Path((project_id, volume_id)): Path<(Uuid, Uuid)>,
    State(state): State<AppState>,
) -> Result<Json<ApiResponse<Volume>>, ApiAppError> {
    require_project_access(&state.db, auth_user.user_id, project_id).await.map_err(ApiAppError)?;
    let volume = sqlx::query_as::<_, Volume>(
        "SELECT id, project_id, service_id, name, mount_path, driver, size_mb, created_at
         FROM volumes
         WHERE id = $1 AND (project_id = $2 OR service_id IN (
             SELECT id FROM services WHERE project_id = $2
         ))",
    )
    .bind(volume_id)
    .bind(project_id)
    .fetch_optional(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?
    .ok_or_else(|| ApiAppError(AppError::NotFound(format!("Volume '{}' not found", volume_id))))?;

    Ok(Json(ApiResponse::ok(volume)))
}

/// POST /projects/:project_id/volumes — create a standalone (project-level)volume
async fn create_project_volume(
    auth_user: AuthUser,
    Path(project_id): Path<Uuid>,
    State(state): State<AppState>,
    Json(body): Json<CreateVolumeRequest>,
) -> Result<(StatusCode, Json<ApiResponse<Volume>>), ApiAppError> {
    require_project_permission(&state.db, auth_user.user_id, project_id, "volume:write").await.map_err(ApiAppError)?;
    if body.name.is_empty() {
        return Err(ApiAppError(AppError::BadRequest("name is required".to_string())));
    }
    if body.mount_path.is_empty() {
        return Err(ApiAppError(AppError::BadRequest("mount_path is required".to_string())));
    }

    let org_row: Option<(Uuid,)> = sqlx::query_as::<_, (Uuid,)>(
        "SELECT org_id FROM projects WHERE id = $1",
    )
    .bind(project_id)
    .fetch_optional(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    let (org_id,) = org_row.ok_or_else(|| {
        ApiAppError(AppError::NotFound(format!("Project '{}' not found", project_id)))
    })?;

    let driver = body.driver.unwrap_or_else(|| "local".to_string());
    let size_mb = body.size_mb.unwrap_or(0);

    // Create the Docker volume before touching the DB.
    state.docker.create_volume(&body.name, &driver).await
        .map_err(|e| ApiAppError(AppError::Docker(e.to_string())))?;

    let volume = sqlx::query_as::<_, Volume>(
        "INSERT INTO volumes (id, project_id, service_id, name, mount_path, driver, size_mb, created_at)
         VALUES ($1, $2, NULL, $3, $4, $5, $6, NOW())
         RETURNING id, project_id, service_id, name, mount_path, driver, size_mb, created_at",
    )
    .bind(Uuid::now_v7())
    .bind(project_id)
    .bind(&body.name)
    .bind(&body.mount_path)
    .bind(&driver)
    .bind(size_mb)
    .fetch_one(&state.db)
    .await
    .map_err(|e| {
        let name = body.name.clone();
        let docker = state.docker.clone();
        tokio::spawn(async move {
            if let Err(re) = docker.remove_volume(&name).await {
                tracing::warn!("Failed to remove orphaned Docker volume '{name}': {re}");
            }
        });
        ApiAppError(AppError::Database(e.to_string()))
    })?;

    let topic = shipyard_mqtt::topics::topology(org_id, project_id);
    let payload = MqttPayload::new("topology.changed")
        .with_meta(serde_json::json!({ "resource": "volume", "volume_id": volume.id }));
    state.mqtt.publish_status(&topic, &payload).await.ok();

    Ok((StatusCode::CREATED, Json(ApiResponse::ok(volume))))
}

/// DELETE /projects/:project_id/volumes/:volume_id — delete a standalone project-level volume
async fn delete_project_volume(
    auth_user: AuthUser,
    Path((project_id, volume_id)): Path<(Uuid, Uuid)>,
    State(state): State<AppState>,
) -> Result<Json<ApiResponse<serde_json::Value>>, ApiAppError> {
    require_project_permission(&state.db, auth_user.user_id, project_id, "volume:write").await.map_err(ApiAppError)?;
    let row: Option<(String, Uuid)> = sqlx::query_as::<_, (String, Uuid)>(
        "SELECT v.name, p.org_id
         FROM volumes v
         JOIN projects p ON p.id = v.project_id
         WHERE v.id = $1 AND v.project_id = $2 AND v.service_id IS NULL",
    )
    .bind(volume_id)
    .bind(project_id)
    .fetch_optional(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    let (volume_name, org_id) = row.ok_or_else(|| {
        ApiAppError(AppError::NotFound(format!("Volume '{}' not found", volume_id)))
    })?;

    match state.docker.remove_volume(&volume_name).await {
        Ok(_) => {}
        Err(AppError::Docker(ref msg)) if msg.contains("404") => {
            tracing::warn!("Volume '{volume_name}' not found in Docker (already removed), cleaning up DB");
        }
        Err(e) => return Err(ApiAppError(e)),
    }

    sqlx::query("DELETE FROM volumes WHERE id = $1 AND project_id = $2 AND service_id IS NULL")
        .bind(volume_id)
        .bind(project_id)
        .execute(&state.db)
        .await
        .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    let topic = shipyard_mqtt::topics::topology(org_id, project_id);
    let payload = MqttPayload::new("topology.changed")
        .with_meta(serde_json::json!({ "resource": "volume", "action": "deleted", "volume_id": volume_id }));
    state.mqtt.publish_status(&topic, &payload).await.ok();

    Ok(Json(ApiResponse::ok(serde_json::json!({ "message": "Volume deleted successfully" }))))
}

// ─── Network Handlers ─────────────────────────────────────────────────────────

/// GET /projects/:project_id/networks
async fn list_networks(
    auth_user: AuthUser,
    Path(project_id): Path<Uuid>,
    State(state): State<AppState>,
) -> Result<Json<ApiResponse<Vec<Network>>>, ApiAppError> {
    require_project_access(&state.db, auth_user.user_id, project_id).await.map_err(ApiAppError)?;
    let networks = sqlx::query_as::<_, Network>(
        "SELECT id, project_id, name, driver, subnet, docker_network_id, created_at
         FROM networks
         WHERE project_id = $1
         ORDER BY created_at ASC",
    )
    .bind(project_id)
    .fetch_all(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    Ok(Json(ApiResponse::ok(networks)))
}

/// GET /projects/:project_id/networks/:network_id
async fn get_network(
    auth_user: AuthUser,
    Path((project_id, network_id)): Path<(Uuid, Uuid)>,
    State(state): State<AppState>,
) -> Result<Json<ApiResponse<Network>>, ApiAppError> {
    require_project_access(&state.db, auth_user.user_id, project_id).await.map_err(ApiAppError)?;
    let network = sqlx::query_as::<_, Network>(
        "SELECT id, project_id, name, driver, subnet, docker_network_id, created_at
         FROM networks
         WHERE id = $1 AND project_id = $2",
    )
    .bind(network_id)
    .bind(project_id)
    .fetch_optional(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?
    .ok_or_else(|| ApiAppError(AppError::NotFound(format!("Network '{}' not found", network_id))))?;

    Ok(Json(ApiResponse::ok(network)))
}

/// POST /projects/:project_id/networks
async fn create_network(
    auth_user: AuthUser,
    Path(project_id): Path<Uuid>,
    State(state): State<AppState>,
    Json(body): Json<CreateNetworkRequest>,
) -> Result<(StatusCode, Json<ApiResponse<Network>>), ApiAppError> {
    require_project_permission(&state.db, auth_user.user_id, project_id, "network:write").await.map_err(ApiAppError)?;
    if body.name.is_empty() {
        return Err(ApiAppError(AppError::BadRequest("name is required".to_string())));
    }

    let org_row: Option<(Uuid,)> = sqlx::query_as::<_, (Uuid,)>(
        "SELECT org_id FROM projects WHERE id = $1",
    )
    .bind(project_id)
    .fetch_optional(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    let (org_id,) = org_row.ok_or_else(|| {
        ApiAppError(AppError::NotFound(format!("Project '{}' not found", project_id)))
    })?;

    let driver = body.driver.unwrap_or_else(|| "overlay".to_string());
    let subnet = body.subnet.unwrap_or_default();

    // Create the Docker network first; this returns the Docker-assigned network ID.
    let docker_network_id = state.docker.create_network(&body.name, &driver).await
        .map_err(|e| ApiAppError(AppError::Docker(e.to_string())))?;

    let network = sqlx::query_as::<_, Network>(
        "INSERT INTO networks (id, project_id, name, driver, subnet, docker_network_id, created_at)
         VALUES ($1, $2, $3, $4, $5, $6, NOW())
         RETURNING id, project_id, name, driver, subnet, docker_network_id, created_at",
    )
    .bind(Uuid::now_v7())
    .bind(project_id)
    .bind(&body.name)
    .bind(&driver)
    .bind(&subnet)
    .bind(&docker_network_id)
    .fetch_one(&state.db)
    .await
    .map_err(|e| {
        let msg = e.to_string();
        // Best-effort cleanup of the Docker network on DB failure.
        let docker_id = docker_network_id.clone();
        let docker = state.docker.clone();
        tokio::spawn(async move {
            if let Err(re) = docker.remove_network(&docker_id).await {
                tracing::warn!("Failed to remove orphaned Docker network '{docker_id}': {re}");
            }
        });
        if msg.contains("unique") || msg.contains("duplicate") {
            ApiAppError(AppError::Conflict(format!(
                "A network named '{}' already exists in this project",
                body.name
            )))
        } else {
            ApiAppError(AppError::Database(msg))
        }
    })?;

    let topic = shipyard_mqtt::topics::topology(org_id, project_id);
    let payload = MqttPayload::new("topology.changed")
        .with_meta(serde_json::json!({ "resource": "network", "network_id": network.id }));
    state.mqtt.publish_status(&topic, &payload).await.ok();

    Ok((StatusCode::CREATED, Json(ApiResponse::ok(network))))
}

/// POST /projects/:project_id/networks/:network_id/attach
async fn attach_service(
    auth_user: AuthUser,
    Path((project_id, network_id)): Path<(Uuid, Uuid)>,
    State(state): State<AppState>,
    Json(body): Json<AttachServiceRequest>,
) -> Result<Json<ApiResponse<serde_json::Value>>, ApiAppError> {
    require_project_permission(&state.db, auth_user.user_id, project_id, "network:write").await.map_err(ApiAppError)?;
    // Verify network belongs to this project
    let network_exists: Option<(bool,)> = sqlx::query_as::<_, (bool,)>(
        "SELECT TRUE FROM networks WHERE id = $1 AND project_id = $2",
    )
    .bind(network_id)
    .bind(project_id)
    .fetch_optional(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    if network_exists.is_none() {
        return Err(ApiAppError(AppError::NotFound(format!(
            "Network '{}' not found in project '{}'",
            network_id, project_id
        ))));
    }

    // Verify service exists
    let service_exists: Option<(bool,)> = sqlx::query_as::<_, (bool,)>(
        "SELECT TRUE FROM services WHERE id = $1",
    )
    .bind(body.service_id)
    .fetch_optional(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    if service_exists.is_none() {
        return Err(ApiAppError(AppError::NotFound(format!(
            "Service '{}' not found",
            body.service_id
        ))));
    }

    sqlx::query(
        "INSERT INTO service_networks (service_id, network_id) VALUES ($1, $2)
         ON CONFLICT (service_id, network_id) DO NOTHING",
    )
    .bind(body.service_id)
    .bind(network_id)
    .execute(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    Ok(Json(ApiResponse::ok(serde_json::json!({
        "message": "Service attached to network successfully",
        "service_id": body.service_id,
        "network_id": network_id,
    }))))
}

/// GET /services/:service_id/networks — list networks a service is attached to
async fn list_service_networks(
    auth_user: AuthUser,
    Path(service_id): Path<Uuid>,
    State(state): State<AppState>,
) -> Result<Json<ApiResponse<Vec<Network>>>, ApiAppError> {
    require_service_access(&state.db, auth_user.user_id, service_id).await.map_err(ApiAppError)?;
    let networks = sqlx::query_as::<_, Network>(
        "SELECT n.id, n.project_id, n.name, n.driver, n.subnet, n.docker_network_id, n.created_at
         FROM networks n
         JOIN service_networks sn ON sn.network_id = n.id
         WHERE sn.service_id = $1
         ORDER BY n.created_at ASC",
    )
    .bind(service_id)
    .fetch_all(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    Ok(Json(ApiResponse::ok(networks)))
}

/// DELETE /projects/:project_id/networks/:network_id/services/:service_id
/// Detaches a service from a network without deleting the network itself.
async fn detach_service(
    auth_user: AuthUser,
    Path((project_id, network_id, service_id)): Path<(Uuid, Uuid, Uuid)>,
    State(state): State<AppState>,
) -> Result<Json<ApiResponse<serde_json::Value>>, ApiAppError> {
    require_project_permission(&state.db, auth_user.user_id, project_id, "network:write").await.map_err(ApiAppError)?;

    let rows = sqlx::query(
        "DELETE FROM service_networks WHERE network_id = $1 AND service_id = $2",
    )
    .bind(network_id)
    .bind(service_id)
    .execute(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?
    .rows_affected();

    if rows == 0 {
        return Err(ApiAppError(AppError::NotFound(format!(
            "Service '{}' is not attached to network '{}'",
            service_id, network_id
        ))));
    }

    Ok(Json(ApiResponse::ok(serde_json::json!({
        "message": "Service detached from network",
        "service_id": service_id,
        "network_id": network_id,
    }))))
}

/// DELETE /projects/:project_id/networks/:network_id
async fn delete_network(
    auth_user: AuthUser,
    Path((project_id, network_id)): Path<(Uuid, Uuid)>,
    State(state): State<AppState>,
) -> Result<Json<ApiResponse<serde_json::Value>>, ApiAppError> {
    require_project_permission(&state.db, auth_user.user_id, project_id, "network:write").await.map_err(ApiAppError)?;
    // Fetch the docker_network_id before deleting so we can remove it from Docker.
    let row: Option<(Option<String>,)> = sqlx::query_as::<_, (Option<String>,)>(
        "SELECT docker_network_id FROM networks WHERE id = $1 AND project_id = $2",
    )
    .bind(network_id)
    .bind(project_id)
    .fetch_optional(&state.db)
    .await
    .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    let (docker_network_id,) = row.ok_or_else(|| {
        ApiAppError(AppError::NotFound(format!("Network '{}' not found", network_id)))
    })?;

    // Remove from Docker. A 404 means it's already gone — skip and clean up DB.
    // Other errors (e.g., active endpoints) are still surfaced to the caller.
    if let Some(docker_id) = &docker_network_id {
        match state.docker.remove_network(docker_id).await {
            Ok(_) => {}
            Err(AppError::Docker(ref msg)) if msg.contains("404") => {
                tracing::warn!("Network '{docker_id}' not found in Docker (already removed), cleaning up DB");
            }
            Err(e) => return Err(ApiAppError(e)),
        }
    }

    sqlx::query("DELETE FROM networks WHERE id = $1 AND project_id = $2")
        .bind(network_id)
        .bind(project_id)
        .execute(&state.db)
        .await
        .map_err(|e| ApiAppError(AppError::Database(e.to_string())))?;

    Ok(Json(ApiResponse::ok(serde_json::json!({ "message": "Network deleted successfully" }))))
}
